### ISSUE TITLE
The type passed to Ep.belongsTo must be defined ember.js?

### ISSUE THREAD

**Issue by xnjiang** [getoutreach/epf#24] opened 2013-07-22 09:30 UTC
I am using emberjs with rails. just converted model to use epf, but encountered:

Assertion failed: The type passed to Ep.belongsTo must be defined ember.js?body=1:364
(anonymous function) ember.js?body=1:364
Ember.assert ember.js?body=1:52
Ep.belongsTo epf.js?body=1:1649
(anonymous function) avatar.js?body=1:12
(anonymous function)

But I have defined the type:

Yu.Avatar = Ep.Model.extend
  active: Ep.attr('boolean')
  image:  Ep.attr('string')
  cropX:  Ep.attr('number')
  cropY:  Ep.attr('number')
  cropW:  Ep.attr('number')
  cropH:  Ep.attr('number')

  imageMediumUrl: Ep.attr('string')
  imageLargeUrl:  Ep.attr('string')
  canManage:      Ep.attr('boolean')

  user: Ep.belongsTo(Yu.User)

Yu.User = Ep.Model.extend
  email: Ep.attr('string')

  avatar:    Ep.belongsTo(Yu.Avatar)
  basicinfo: Ep.belongsTo(Yu.Basicinfo)

Thanks.

**Comment by denisnazarov** [comment] 2013-07-22 17:53
I think you have to specify the relationship in `Yu.User.reopen`.

Take a look here:
https://github.com/GroupTalent/epf/issues/4

``` javascript
Yu.User = Ep.Model.extend
  email: Ep.attr('string')

Yu.User.reopen
  avatar: Ep.hasOne(Yu.Avatar)
  basicinfo: Ep.hasOne(Yu.Basicinfo)
```

**Comment by ghempton** [comment] 2013-07-22 18:08
I am going to close as a dupe of #4

**Closed as completed by ghempton** 2013-07-22 18:08 UTC
Labels: duplicate
