### ISSUE TITLE
Modifying an embedded record doesn't seem to dirty the parent

### ISSUE THREAD

**Issue by whather** [getoutreach/epf#21] opened 2013-07-19 07:24 UTC
I'm trying to modify an embedded record (without modifying the parent record) and then flushing the session. The request never gets sent to the server. The hack work around is to dirty a property on the parent model before the flush.

**Comment by hperl** [comment] 2013-07-22 11:14
I have observed the same issue. For example, I have the following code:

``` javascript
App.Adapter.registerTransform("array", {
  deserialize: function(serialized) {
    return Em.isNone(serialized) ? new Ember.A() : new Ember.A(serialized);
  },
  serialize: function(deserialized) {
    return Em.isNone(deserialized) ? [] : deserialized.toArray();
  }
});

App.Foo = Ep.Model.extend({
  bars: Ep.attr('array')
});

App.FooController = Ember.ObjectController.extend({
  addBar: function(bar) {
    this.get('content.bars').addObject(bar); /* this works fine */
    this.session.flush(); /* yet, model is not dirty, doesn't save */
  }
})
```

The problem with the code is that modifying the `bars` property on a `Foo` model does not make that model dirty. Further, calling `foo.notifyPropertyChange('bars')` blanks out the `bars` property.

Is there a way to manually make a model dirty or forcibly add a model to a session? Better yet, how do I make EPF aware of these changes?

**Comment by ghempton** [comment] 2013-07-22 18:07
@hperl this is only happening in the embedded case right? This is definitely on my radar and will fix. One temporary workaround is to change an attribute on the parent (e.g. `updatedAt`).

**Comment by hperl** [comment] 2013-07-22 18:46
@ghempton yes, this is only in the embedded case, and once I change a non-embedded attribute, the changes in the embedded attribute get serialized and written to the server perfectly.

I already did some debugging but I don't quite understand how epf is deciding when a model needs syncing in the end. You do have a `session.modelWillBecomeDirty(model)` function that does _some_ of the work, adding the model to the collection of shadows. So, am I correct that the problem is that the diff between the Client Model and the Client Shadow (1a + 1b in your flowchart) does not consider embedded attributes? If so I could see if I could code up a PR.

**Comment by ghempton** [comment] 2013-07-22 18:50
The `modelWillBecomeDirty` hook is actually only an optimization (to prevent calculating diffs for all models in the session!). When the session is flushed, the adapter performs a diff between the model and it's shadow to determine dirtiness. It is possible that a "dirty" model (as determined by the list of shadows) will ultimately not be saved by adapter (e.g. as would be the case if you changed a property then changed it back to its original value).

The fix here is going to be in the adapter logic (specifically operation.js). I am actually doing work in there and cleaning stuff up and will see if I can get to this.

**Comment by hperl** [comment] 2013-07-23 07:08
From the (limited) debugging I was able to do, it seems like at least some of the trouble comes from the `diff` not considering embedded attributes.

For non-embedded attributes, I saw (correctly):
- Client Model: _new value_
- Client Shadow: _old value_
- Diff: `[attribute-name]`

For embedded attributes, I saw (not correct in my understanding):
- Client Model: _new value_
- Client Shadow: **new value**
- Diff: `[]` (empty)

So somehow, changes to the Client Model directly affect the Shadow, maybe due to some too shallow copy.

Anyway, the flowchart looks really thought-through, and the ability to do three-way merges on the client is very powerful. For a deeper understanding and in order to contribute, it would be really nice to have some explanation of which code is responsible for which numbers. For example, I am wondering where number 4 is hooked up, i.e. when the Model gets copied to the Shadow. Having said that, I really appreciate the good work you do and look forward to a robust alternative to ember-data.

**Comment by ghempton** [comment] 2013-07-23 07:19
Thanks for the kind words. Cleaning everything up and writing a bunch of blog posts is definitely on the roadmap for me over the next few weeks.

Also, I have just pushed some changes to the [edge branch](https://github.com/GroupTalent/epf/tree/edge) and I think that they might actually address the issue. Will merge into master once I have added a few more tests.

**Comment by hperl** [comment] 2013-07-23 11:44
I found that using Ember.copy() fixes the troubles I had with the model not being marked dirty for sync.

**Comment by ghempton** [comment] 2013-07-23 17:24
@hperl I think Wes is referencing a different issue: models that are declared as an embedded relationship through the adapter similar to ED. Your fix is for embedded models declared as an attribute (instead of `hasMany` or `belongsTo`. I think both cases are valid, need to think though.

**Comment by ghempton** [comment] 2013-07-25 23:33
This should be fixed now in master. Will re-open if it is not.

**Closed as completed by ghempton** 2013-07-25 23:33 UTC
Labels: bug
