### ISSUE TITLE
Error "clientId has changed for"

### ISSUE THREAD

**Issue by sebzincktiz** [getoutreach/epf#80] opened 2013-08-27 16:01 UTC
``` <ul>
{{#each user in controller}}    
<li>{{user.name}}</li>
<ul>
{{#each contact in user.contacts}}  
<li>{{contact.name}}</li>
{{/each}}
</ul>
{{/each}}
</ul>
```

These loops trigger multiple GET request (App.Contact.find(id)) and throws the following error.

`clientId has changed for <App.Contact:ember666:[521cca5c8635ff620600000f, contact3]>`

Sometimes it didn't throws any error but HasMany array from User.contacts contains duplicates.

**Comment by sebzincktiz** [comment] 2013-08-28 07:26
Seems to work fine when sideloading user's contacts. Maybe implementing "findMany" will solve the problem.  <a href="https://github.com/GroupTalent/epf/issues/79">Issue #79</a>

**Comment by ghempton** [comment] 2013-08-30 00:59
This definitely feels like a separate bug. Need to find a way to reproduce.

**Comment by ghempton** [comment] 2013-09-13 04:55
EPF has since undergone some pretty big changes. I am going to close this for lack of a repro. Feel free to re-open if you still hit it.

**Closed as completed by ghempton** 2013-09-13 04:55 UTC
